# Generated by Django 5.1.7 on 2025-04-04 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_reservation_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(default='9999999999', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Enter 10 digit contact number', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='UPI', max_length=50),
        ),
    ]
