# Generated by Django 5.2 on 2025-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_reservation_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_status',
            field=models.CharField(choices=[('1', 'booked'), ('0', 'cancelled')], default='0', max_length=10),
        ),
    ]
