# Generated by Django 5.2 on 2025-04-16 05:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_reservation_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'booked'), ('cancelled', 'cancelled')], default='booked', max_length=10),
        ),
        migrations.CreateModel(
            name='AllTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default='0', max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(default='9999999999', max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Enter 10 digit contact number', regex='^\\d{10}$')])),
                ('date', models.DateField()),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('booking_status', models.CharField(choices=[('booked', 'booked'), ('cancelled', 'cancelled')], default='booked', max_length=10)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.table')),
            ],
        ),
    ]
