# Generated by Django 5.2 on 2025-04-16 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_reservation_booking_status_alltransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltransactions',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
