# Generated by Django 5.2 on 2025-04-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alltransactions_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_username',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
