# Generated by Django 5.2 on 2025-04-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_reservation_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='alltransactions',
            name='customer_username',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
