# Generated by Django 5.2 on 2025-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alltransactions',
            name='booking_status',
            field=models.CharField(choices=[('booked', 'booked'), ('canceled', 'canceled')], default='booked', max_length=10),
        ),
    ]
